run:
  timeout: 3m

linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-numbers: "0o666,0o777"
  funlen:
    lines: 77
    statements: 50
  cyclop:
    skip-tests: true
    max-complexity: 12
    package-average: 0
linters:
  enable-all: true
  disable:
    # New で interface を戻り値とすることを許す。
    - ireturn
